[build]
  publish = "."
  command = ""

[dev]
  publish = "."
  port = 3000
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success.html"
  to = "/success.html"
  status = 200
  
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[forms]
  # Define your forms and their fields
  [forms.waitlist]
    name = "waitlist"

  [forms.newsletter]
    name = "newsletter" 